import logging
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
import yfinance as yf
import pandas as pd
import ta
import math
import numpy as np
import requests

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="XAU/USD Trading Strategy API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount the static directory
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
def read_root():
    return FileResponse("static/index.html")

@app.get("/api/market-data")
def get_market_data(period: str = "1y"):
    try:
        # Download Gold Futures and USD/TWD exchange rate
        tickers = "GC=F TWD=X"
        
        data = yf.download(tickers, period=period, progress=False)
        
        # In yfinance >= 0.2.x, download with multiple tickers returns MultiIndex columns
        if data.empty:
            logger.warning("yf.download returned empty data. Trying fallback mechanism...")
            # Fallback: Download individually
            gold_data = yf.download("GC=F", period=period, progress=False)
            twd_data = yf.download("TWD=X", period=period, progress=False)
            
            if gold_data.empty or twd_data.empty:
                # Second Fallback: use Ticker.history()
                gold_data = yf.Ticker("GC=F").history(period=period)
                twd_data = yf.Ticker("TWD=X").history(period=period)
                
                if gold_data.empty or twd_data.empty:
                    return {"error": "No data found. Yahoo Finance might be blocking this server's IP address."}
            
            # Reconstruct the expected MultiIndex DataFrame from individual downloads
            # to match the logic below
            data = pd.DataFrame()
            if isinstance(gold_data.columns, pd.MultiIndex):
                # It's already multi-index
                data = gold_data.join(twd_data, how="outer")
            else:
                # We need to manually map to the expected structure
                data = pd.concat({'GC=F': gold_data, 'TWD=X': twd_data}, axis=1).swaplevel(0, 1, axis=1)
            
        # Ensure we have both tickers
        if "GC=F" not in data['Close'].columns or "TWD=X" not in data['Close'].columns:
             return {"error": "Missing ticker data"}
             
        # Extract closing prices
        df = pd.DataFrame()
        df['gold_usd'] = data['Close']['GC=F']
        df['open'] = data['Open']['GC=F']
        df['high'] = data['High']['GC=F']
        df['low'] = data['Low']['GC=F']
        df['close'] = data['Close']['GC=F']
        df['volume'] = data['Volume']['GC=F']
        
        df['usd_twd'] = data['Close']['TWD=X']
        
        # Forward fill missing values (e.g. if one market is closed)
        df.ffill(inplace=True)
        # Drop rows with remaining NaNs (usually at the very beginning)
        df.dropna(inplace=True)
        
        # Calculate Taiwan Bank Gold Passbook Estimate (TWD/Gram)
        # 1 Troy Ounce = 31.1034768 grams
        # Applying a 1.01 multiplier (~1% premium) for bank spread
        TROY_OUNCE_GRAMS = 31.1034768
        df['twd_per_gram'] = (df['gold_usd'] / TROY_OUNCE_GRAMS) * df['usd_twd'] * 1.01
        
        # Calculate Indicators using the 'ta' library
        # RSI
        df['rsi'] = ta.momentum.RSIIndicator(close=df['gold_usd'], window=14).rsi()
        
        # MACD
        macd = ta.trend.MACD(close=df['gold_usd'])
        df['macd'] = macd.macd()
        df['macd_signal'] = macd.macd_signal()
        df['macd_diff'] = macd.macd_diff()
        
        # SMA
        df['sma_20'] = ta.trend.SMAIndicator(close=df['gold_usd'], window=20).sma_indicator()
        df['sma_50'] = ta.trend.SMAIndicator(close=df['gold_usd'], window=50).sma_indicator()
        
        # Drop NaN generated by indicators (first few rows)
        df.dropna(inplace=True)
        
        # Generate Trading Signal (Current Day)
        latest = df.iloc[-1]
        signal = "HOLD"
        signal_reasons = []
        
        if latest['rsi'] > 70:
            signal_reasons.append("RSI is Overbought (>70)")
        elif latest['rsi'] < 30:
            signal_reasons.append("RSI is Oversold (<30)")
            
        if latest['macd_diff'] > 0 and df.iloc[-2]['macd_diff'] <= 0:
            signal_reasons.append("MACD Bullish Cross")
        elif latest['macd_diff'] < 0 and df.iloc[-2]['macd_diff'] >= 0:
            signal_reasons.append("MACD Bearish Cross")
            
        if latest['sma_20'] > latest['sma_50'] and df.iloc[-2]['sma_20'] <= df.iloc[-2]['sma_50']:
             signal_reasons.append("Golden Cross (SMA20 > SMA50)")
        elif latest['sma_20'] < latest['sma_50'] and df.iloc[-2]['sma_20'] >= df.iloc[-2]['sma_50']:
             signal_reasons.append("Death Cross (SMA20 < SMA50)")
             
        # Basic logic for signal
        bullish_points = sum([1 for r in signal_reasons if "Oversold" in r or "Bullish" in r or "Golden" in r])
        bearish_points = sum([1 for r in signal_reasons if "Overbought" in r or "Bearish" in r or "Death" in r])
        
        if bullish_points > bearish_points:
            signal = "BUY"
        elif bearish_points > bullish_points:
            signal = "SELL"
            
        if not signal_reasons:
            signal_reasons.append("No strong indicator signals currently.")

        # Prepare JSON response
        # Ensure timestamp is string for JSON
        df.index = df.index.astype(str)
        
        # Create records
        records = []
        for index, row in df.iterrows():
            records.append({
                "time": index.split(" ")[0], # YYYY-MM-DD
                "open": float(row['open']),
                "high": float(row['high']),
                "low": float(row['low']),
                "close": float(row['close']),
                "value": float(row['close']), # for line series
                "twd_per_gram": float(row['twd_per_gram']),
                "rsi": float(row['rsi']) if not math.isnan(row['rsi']) else None,
                "macd": float(row['macd']) if not math.isnan(row['macd']) else None,
                "macd_signal": float(row['macd_signal']) if not math.isnan(row['macd_signal']) else None,
                "macd_hist": float(row['macd_diff']) if not math.isnan(row['macd_diff']) else None,
                "sma_20": float(row['sma_20']) if not math.isnan(row['sma_20']) else None,
                "sma_50": float(row['sma_50']) if not math.isnan(row['sma_50']) else None,
            })
            
        return {
            "status": "success",
            "current_price_usd": float(latest['gold_usd']),
            "current_price_twd": float(latest['twd_per_gram']),
            "exchange_rate": float(latest['usd_twd']),
            "signal": signal,
            "reasons": signal_reasons,
            "history": records
        }
        
    except Exception as e:
        logger.error(f"Error fetching data: {e}")
        return {"error": str(e)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
